server:
  port: 8081

spring:
  application:
    name: movie-catalog-service
  cache:
    redis: 
      cache-null-values: false
      time-to-live: 10000
      use-key-prefix: true
  redis:
    host: localhost
    port: 6379
    timeout: 200
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/